name: PlaceMC
version: 0.0.1
author: JJJollyjim <jamie.mcclymont@gmail.com>
main: com.kwiius.placemc.PluginMain
commands:
  goto:
    description: Teleport to a position
    usage: /goto x y
  generate:
    description: Places the background square of white wool
    usage: /generate
    permission: placemc.generate
    permission-message: You don't have <permission>
permissions:
  placemc.generate:
    description: Access to generate wool
    default: op